import React, { useMemo, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { apiFetch, formatNumber } from '../api.js'
import { validateNumericInput } from '../lib/validation.js'
import { exportDynamicCsv, parseDynamicCsv, downloadCsv } from '../lib/csv-engine.js'

const STANDARD_FIELDS=new Set(['category_code','material_name','weight_kg','quantity','unit','unit_price','amount','notes'])
const initialValues=fields=>Object.fromEntries(fields.map(field=>[field.field_key,'']))

export default function DynamicModuleEntry({definition,month,permissions=[]}){
  const qc=useQueryClient(); const can=p=>permissions.includes(p); const [values,setValues]=useState(()=>initialValues(definition.fields||[])); const [entryDate,setEntryDate]=useState(`${month}-01`); const [editingId,setEditingId]=useState(''); const [message,setMessage]=useState(''); const [csvPreview,setCsvPreview]=useState([])
  const query=useQuery({queryKey:['entries',definition.code,month],queryFn:()=>apiFetch(`/api/entries?module=${definition.code}&month=${month}`)})
  const rows=query.data||[]; const fields=useMemo(()=>definition.fields||[],[definition.fields])
  const save=useMutation({mutationFn:payload=>apiFetch(payload.id?`/api/entries/${payload.id}`:'/api/entries',{method:payload.id?'PUT':'POST',body:JSON.stringify(payload)}),onSuccess:()=>{qc.invalidateQueries({queryKey:['entries']});setValues(initialValues(fields));setEditingId('');setMessage('บันทึกสำเร็จ')},onError:e=>setMessage(e.message)})
  const remove=useMutation({mutationFn:id=>apiFetch(`/api/entries/${id}`,{method:'DELETE'}),onSuccess:()=>qc.invalidateQueries({queryKey:['entries']})})
  const importBatch=useMutation({mutationFn:payload=>apiFetch('/api/entries/batch',{method:'POST',body:JSON.stringify({entries:payload})}),onSuccess:()=>{setCsvPreview([]);qc.invalidateQueries({queryKey:['entries']})},onError:e=>setMessage(e.message)})
  const setValue=(field,value)=>setValues(prev=>({...prev,[field.field_key]:value}))
  const submit=e=>{e.preventDefault();setMessage('');const standard={};const custom={}
    for(const field of fields){let value=values[field.field_key];if(field.required&&(value===''||value==null))return setMessage(`กรุณากรอก${field.label_th}`)
      if(['integer','decimal'].includes(field.data_type)&&value!==''){const checked=validateNumericInput(value,{integer:field.data_type==='integer',label:field.label_th,min:field.validation?.min??0});if(checked.error)return setMessage(checked.error);value=checked.number}
      if(STANDARD_FIELDS.has(field.field_key))standard[field.field_key]=value===''?null:value;else custom[field.field_key]=value
    }
    const payload={id:editingId||undefined,module:definition.code,entry_date:definition.input_mode==='monthly'||definition.input_mode==='daily_average'?`${month}-01`:entryDate,period_month:`${month}-01`,material_name:standard.material_name||definition.name_th,unit:standard.unit||definition.default_unit||'',...standard,metadata:{input_mode:definition.input_mode,dynamic_fields:custom}}
    save.mutate(payload)
  }
  const edit=row=>{const custom=row.metadata?.dynamic_fields||{};setEditingId(row.id);setEntryDate(row.entry_date);setValues(Object.fromEntries(fields.map(field=>[field.field_key,row[field.field_key]??custom[field.field_key]??''])))}
  const exportCsv=()=>downloadCsv(exportDynamicCsv(rows,definition,month),`${definition.code.toUpperCase()}_${month}.csv`)
  const importCsv=async event=>{const file=event.target.files?.[0];event.target.value='';if(!file)return;try{setCsvPreview(parseDynamicCsv(await file.text(),definition,month))}catch(error){setMessage(error.message)}}
  const confirmImport=()=>{if(csvPreview.some(r=>r.errors.length))return;const payload=csvPreview.map(item=>{const standard={};const custom={};for(const field of fields)(STANDARD_FIELDS.has(field.field_key)?standard:custom)[field.field_key]=item.values[field.field_key]??null;return{id:item.id,module:definition.code,entry_date:item.date,period_month:`${month}-01`,material_name:standard.material_name||definition.name_th,unit:standard.unit||definition.default_unit||'',...standard,metadata:{input_mode:definition.input_mode,dynamic_fields:custom}}});importBatch.mutate(payload)}
  if(definition.input_mode==='calculated')return <div className="card"><h3>{definition.name_th}</h3><div className="alert">หมวดคำนวณอัตโนมัติ จะแสดงผลจากสูตรใน M4</div></div>
  return <div style={{display:'grid',gap:16}}><div className="card"><div className="section-title-row"><div><h3>{definition.name_th}</h3><p className="muted">{definition.description||`ฟอร์มจาก Metadata · ${definition.input_mode}`}</p></div><div style={{display:'flex',gap:8}}>{definition.allow_csv_import&&can('entries.import')&&<label className="ghost" style={{cursor:'pointer'}}>นำเข้า CSV<input type="file" accept=".csv,text/csv" hidden onChange={importCsv}/></label>}{definition.allow_csv_export&&can('entries.export')&&<button className="ghost" onClick={exportCsv}>ส่งออก CSV</button>}</div></div>
    {message&&<div className={save.isError?'alert error':'alert'}>{message}</div>}<form onSubmit={submit} style={{display:'grid',gap:12}}>{!['monthly','daily_average'].includes(definition.input_mode)&&<label className="field"><span>วันที่</span><input type="date" value={entryDate} min={`${month}-01`} max={`${month}-31`} onChange={e=>setEntryDate(e.target.value)} required/></label>}
      {fields.map(field=><label className="field" key={field.field_key}><span>{field.label_th}{field.required?' *':''}</span>{field.data_type==='select'?<select value={values[field.field_key]??''} onChange={e=>setValue(field,e.target.value)}><option value="">เลือก</option>{(field.options||[]).map(option=><option key={typeof option==='string'?option:option.value} value={typeof option==='string'?option:option.value}>{typeof option==='string'?option:option.label}</option>)}</select>:field.data_type==='boolean'?<input type="checkbox" checked={Boolean(values[field.field_key])} onChange={e=>setValue(field,e.target.checked)}/>:<input type={field.data_type==='date'?'date':field.data_type==='month'?'month':'text'} inputMode={['integer','decimal'].includes(field.data_type)?'decimal':undefined} value={values[field.field_key]??''} onChange={e=>setValue(field,e.target.value)} placeholder={field.placeholder||''}/>} {field.unit&&<small className="muted">หน่วย: {field.unit}</small>}</label>)}
      <div className="form-actions bottom-actions">{editingId&&<button type="button" className="ghost" onClick={()=>{setEditingId('');setValues(initialValues(fields))}}>ยกเลิก</button>}<button className="primary" disabled={!can(editingId?'entries.edit':'entries.create')||save.isPending}>{save.isPending?'กำลังบันทึก...':editingId?'บันทึกการแก้ไข':'บันทึกข้อมูล'}</button></div></form></div>
    {csvPreview.length>0&&<div className="card"><h3>ตรวจสอบ CSV ก่อนนำเข้า</h3><div className="table-wrap"><table><thead><tr><th>แถว</th><th>วันที่</th><th>สถานะ</th></tr></thead><tbody>{csvPreview.map(r=><tr key={r.line}><td>{r.line}</td><td>{r.date}</td><td style={{color:r.errors.length?'#dc2626':'#15803d'}}>{r.errors.join(', ')||'พร้อมนำเข้า'}</td></tr>)}</tbody></table></div><div className="form-actions bottom-actions"><button className="ghost" onClick={()=>setCsvPreview([])}>ยกเลิก</button><button className="primary" disabled={csvPreview.some(r=>r.errors.length)||importBatch.isPending} onClick={confirmImport}>ยืนยันนำเข้า</button></div></div>}
    <div className="card"><h3>ข้อมูลเดือนนี้</h3><div className="table-wrap"><table><thead><tr><th>วันที่</th>{fields.map(f=><th key={f.field_key}>{f.label_th}</th>)}<th>จัดการ</th></tr></thead><tbody>{rows.map(row=>{const custom=row.metadata?.dynamic_fields||{};return <tr key={row.id}><td>{row.entry_date}</td>{fields.map(f=><td key={f.field_key}>{typeof (row[f.field_key]??custom[f.field_key])==='number'?formatNumber(row[f.field_key]??custom[f.field_key]):String(row[f.field_key]??custom[f.field_key]??'')}</td>)}<td><button className="tiny" onClick={()=>edit(row)}>แก้ไข</button> <button className="danger tiny" disabled={!can('entries.delete')} onClick={()=>confirm('ลบรายการนี้หรือไม่?')&&remove.mutate(row.id)}>ลบ</button></td></tr>})}{!rows.length&&<tr><td colSpan={fields.length+2} className="muted">ยังไม่มีข้อมูล</td></tr>}</tbody></table></div></div></div>
}
