import React, { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { Plus, Trash2 } from 'lucide-react'
import { apiFetch } from '../api.js'
import { COMMON_UNITS } from '../lib/unit-suggestions.js'

const emptyModule={code:'',name_th:'',description:'',input_mode:'monthly',icon_key:'package',color:'#3B82F6',primary_metric:'quantity',default_unit:'',aggregation:'sum',better_direction:'neutral',allow_csv_import:true,allow_csv_export:true,active:true,sort_order:100,fields:[]}
const emptyField=()=>({field_key:'',label_th:'',data_type:'decimal',required:false,unit:'',placeholder:'',options_text:'',validation:{min:0},active:true})

export default function ModuleBuilder(){
  const qc=useQueryClient(); const [form,setForm]=useState(emptyModule); const [message,setMessage]=useState(''); const [editingCode,setEditingCode]=useState('')
  const query=useQuery({queryKey:['metadata-modules'],queryFn:()=>apiFetch('/api/modules')})
  const refreshModuleViews=()=>{qc.invalidateQueries({queryKey:['metadata-modules']});qc.invalidateQueries({predicate:query=>String(query.queryKey[0]||'').startsWith('modules-active')})}
  const create=useMutation({mutationFn:payload=>apiFetch('/api/modules',{method:'POST',body:JSON.stringify(payload)}),onSuccess:()=>{setForm(emptyModule);setMessage('เพิ่มหมวดหลักสำเร็จ');refreshModuleViews()},onError:e=>setMessage(e.message)})
  const update=useMutation({mutationFn:({code,patch})=>apiFetch(`/api/modules/${code}`,{method:'PUT',body:JSON.stringify(patch)}),onSuccess:()=>{refreshModuleViews();if(editingCode){setEditingCode('');setForm(emptyModule);setMessage('แก้ไขหมวดหลักสำเร็จ')}} ,onError:e=>setMessage(e.message)})
  const setField=(index,patch)=>setForm(prev=>({...prev,fields:prev.fields.map((field,i)=>i===index?{...field,...patch}:field)}))
  const submit=e=>{e.preventDefault();setMessage('');const payload={...form,code:form.code.trim().toLowerCase(),name_th:form.name_th.trim(),default_unit:form.default_unit||null,fields:form.fields.map((f,i)=>{const {options_text,...field}=f;return{...field,field_key:f.field_key.trim().toLowerCase(),label_th:f.label_th.trim(),unit:f.unit||null,placeholder:f.placeholder||null,options:f.data_type==='select'?options_text.split(',').map(value=>value.trim()).filter(Boolean):[],sort_order:(i+1)*10}})};if(editingCode)update.mutate({code:editingCode,patch:payload});else create.mutate(payload)}
  const editModule=m=>{setEditingCode(m.code);setMessage('');setForm({...emptyModule,...m,fields:(m.fields||[]).map(f=>({field_key:f.field_key,label_th:f.label_th,data_type:f.data_type,required:f.required,unit:f.unit||'',placeholder:f.placeholder||'',options_text:(f.options||[]).map(option=>typeof option==='string'?option:option.label).join(', '),validation:f.validation||{},active:f.active}))})}
  return <div style={{display:'grid',gap:18}}>
    <div className="card"><h3>Module Builder</h3><p className="muted">เพิ่มหมวดหลักและกำหนดช่องข้อมูล ระบบจะสร้างฟอร์ม ตาราง Dashboard และสิทธิ์รายโมดูลจาก Metadata</p>
      {message&&<div className={create.isError?'alert error':'alert'}>{message}</div>}
      <form onSubmit={submit} style={{display:'grid',gap:12}}>
        <div className="split-grid"><label className="field"><span>รหัสหมวด (อังกฤษ)</span><input value={form.code} onChange={e=>setForm({...form,code:e.target.value})} placeholder="เช่น water" required pattern="[a-z][a-z0-9_]*"/></label><label className="field"><span>ชื่อหมวดภาษาไทย</span><input value={form.name_th} onChange={e=>setForm({...form,name_th:e.target.value})} required/></label></div>
        <label className="field"><span>คำอธิบาย</span><input value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>
        <div className="split-grid"><label className="field"><span>รูปแบบบันทึก</span><select value={form.input_mode} onChange={e=>setForm({...form,input_mode:e.target.value})}>{[['daily','รายวัน'],['monthly','รายเดือน'],['daily_average','ค่าเฉลี่ยรายวัน'],['transaction','รายการธุรกรรม'],['multi_row','หลายรายการ'],['hybrid','รายวัน/รายเดือน'],['calculated','คำนวณอัตโนมัติ']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label className="field"><span>วิธีสรุป</span><select value={form.aggregation} onChange={e=>setForm({...form,aggregation:e.target.value})}>{['sum','average','latest','count','calculated'].map(v=><option key={v}>{v}</option>)}</select></label></div>
        <div className="split-grid"><label className="field"><span>ตัวชี้วัดหลัก</span><input value={form.primary_metric} onChange={e=>setForm({...form,primary_metric:e.target.value})}/></label><label className="field"><span>หน่วยเริ่มต้น</span><input list="module-units" value={form.default_unit} onChange={e=>setForm({...form,default_unit:e.target.value})}/><datalist id="module-units">{COMMON_UNITS.map(u=><option key={u} value={u}/>)}</datalist></label></div>
        <div className="section-title-row"><h4>ช่องข้อมูล</h4><button type="button" className="ghost" onClick={()=>setForm(prev=>({...prev,fields:[...prev.fields,emptyField()]}))}><Plus size={15}/> เพิ่มช่อง</button></div>
        {form.fields.map((field,index)=><div key={index} className="module-field-editor"><label className="field"><span>Field key</span><input value={field.field_key} onChange={e=>setField(index,{field_key:e.target.value})} required/></label><label className="field"><span>ชื่อช่อง</span><input value={field.label_th} onChange={e=>setField(index,{label_th:e.target.value})} required/></label><label className="field"><span>ชนิด</span><select value={field.data_type} onChange={e=>setField(index,{data_type:e.target.value})}>{['text','integer','decimal','date','month','select','boolean','calculated'].map(v=><option key={v}>{v}</option>)}</select></label><label className="field"><span>หน่วย</span><input list="module-units" value={field.unit} onChange={e=>setField(index,{unit:e.target.value})}/></label>{field.data_type==='select'&&<label className="field field-span"><span>ตัวเลือก (คั่นด้วยจุลภาค)</span><input value={field.options_text} onChange={e=>setField(index,{options_text:e.target.value})} placeholder="เช่น ขวด, กระดาษ, โลหะ" required/></label>}<button type="button" className="danger tiny" onClick={()=>setForm(prev=>({...prev,fields:prev.fields.filter((_,i)=>i!==index)}))}><Trash2 size={14}/></button></div>)}
        <div className="form-actions bottom-actions">{editingCode&&<button type="button" className="ghost" onClick={()=>{setEditingCode('');setForm(emptyModule)}}>ยกเลิกแก้ไข</button>}<button className="primary" disabled={create.isPending||update.isPending}>{create.isPending||update.isPending?'กำลังบันทึก...':editingCode?'บันทึกการแก้ไข':'บันทึกหมวดหลัก'}</button></div>
      </form>
    </div>
    <div className="card"><h3>หมวดหลักจาก Metadata</h3>{query.error&&<div className="alert error">{query.error.message}</div>}<div className="table-wrap"><table><thead><tr><th>ลำดับ</th><th>หมวด</th><th>รูปแบบ</th><th>ช่อง</th><th>จัดการ</th></tr></thead><tbody>{(query.data||[]).map(m=><tr key={m.code}><td>{m.sort_order}</td><td><strong>{m.name_th}</strong><br/><code>{m.code}</code></td><td>{m.input_mode}</td><td>{m.fields?.length||0}</td><td><button className="tiny" onClick={()=>editModule(m)}>แก้ไข</button> <button className="tiny" onClick={()=>update.mutate({code:m.code,patch:{active:!m.active}})}>{m.active?'เปิด':'ปิด'}</button></td></tr>)}</tbody></table></div></div>
  </div>
}
