import React, { useEffect, useMemo, useState } from 'react'
import { useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, CheckCircle2, FileSpreadsheet, History, RotateCcw, UploadCloud } from 'lucide-react'
import { apiFetch, formatNumber, MODULE_LABELS } from '../api.js'

const STATUS = { ready:'พร้อมนำเข้า', review:'ต้องตรวจสอบ', duplicate:'มีในฐานข้อมูลแล้ว' }

export default function MultiSheetImport({ permissions = [], user }) {
  const queryClient=useQueryClient()
  const [file,setFile]=useState(null), [preview,setPreview]=useState(null), [selected,setSelected]=useState(new Set())
  const [filter,setFilter]=useState('all'), [history,setHistory]=useState([]), [busy,setBusy]=useState(false)
  const [error,setError]=useState(''), [success,setSuccess]=useState('')
  const canRollback=user?.role==='owner'||permissions.includes('entries.delete')
  const loadHistory=async()=>{try{setHistory(await apiFetch('/api/imports/multi-sheet/history'))}catch(e){if(!/P3_MULTI_SHEET/i.test(e.message))setError(e.message)}}
  useEffect(()=>{loadHistory()},[])
  async function analyze(){if(!file)return setError('กรุณาเลือกไฟล์ .xlsx');setBusy(true);setError('');setSuccess('');try{const form=new FormData();form.append('file',file);const result=await apiFetch('/api/imports/multi-sheet/preview',{method:'POST',body:form});setPreview(result);setSelected(new Set(result.rows.filter(r=>r.status==='ready').map(r=>r.row_id)))}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function commit(){const rows=(preview?.rows||[]).filter(r=>r.status==='ready'&&selected.has(r.row_id));if(!rows.length)return setError('ไม่มีรายการพร้อมนำเข้า');if(!window.confirm(`ยืนยันนำเข้าทั้ง ${rows.length} รายการในครั้งเดียว?`))return;setBusy(true);setError('');try{const result=await apiFetch('/api/imports/multi-sheet/commit',{method:'POST',body:JSON.stringify({file_name:preview.file_name,file_hash:preview.file_hash,preview_summary:preview.summary,rows:rows.map(r=>({source_key:r.source_key,entry:r.entry}))})});setSuccess(`นำเข้าสำเร็จ ${result.imported} รายการ · ข้ามข้อมูลเดิม ${result.skipped}`);await queryClient.invalidateQueries({queryKey:['entries']});setPreview(null);setFile(null);setSelected(new Set());await loadHistory()}catch(e){setError(e.message)}finally{setBusy(false)}}
  async function rollback(batch){if(!window.confirm(`ย้อนกลับ ${batch.imported_rows} รายการจากไฟล์ ${batch.file_name}?`))return;setBusy(true);setError('');try{const result=await apiFetch(`/api/imports/multi-sheet/${batch.id}/rollback`,{method:'POST',body:'{}'});setSuccess(`ย้อนกลับสำเร็จ ${result.removed} รายการ`);await queryClient.invalidateQueries({queryKey:['entries']});await loadHistory()}catch(e){setError(e.message)}finally{setBusy(false)}}
  const visible=useMemo(()=>(preview?.rows||[]).filter(r=>filter==='all'||r.sheet===filter),[preview,filter])
  return <section className="page">
    <div className="page-header"><div><p className="eyebrow">One-shot Database Import</p><h2>นำเข้าข้อมูลรวม Excel</h2><p className="muted">อ่าน ขยะ RDF · ทิชชู่ · ถุงขยะ · อาหารหมา จากไฟล์เดียว แยกประเภทและเดือนให้อัตโนมัติ</p></div></div>
    {error&&<div className="alert error"><AlertTriangle size={18}/>{error}</div>}{success&&<div className="alert success"><CheckCircle2 size={18}/>{success}</div>}
    {!preview&&<div className="card" style={{maxWidth:800}}><div style={{display:'flex',gap:16,alignItems:'center',flexWrap:'wrap'}}><span className="tool-nav-icon"><FileSpreadsheet size={28}/></span><div style={{flex:1,minWidth:240}}><h3>เลือกไฟล์ Excel รวม</h3><p className="muted">รองรับ .xlsx สูงสุด 15 MB และอ่านทุกแท็บที่รู้จักในครั้งเดียว</p></div><label className="ghost" style={{cursor:'pointer'}}><UploadCloud size={17}/> เลือกไฟล์<input type="file" accept=".xlsx" hidden onChange={e=>setFile(e.target.files?.[0]||null)}/></label></div>{file&&<div className="import-file-name">{file.name} · {formatNumber(file.size/1024,1)} KB</div>}<div className="form-actions bottom-actions"><button className="primary" disabled={!file||busy} onClick={analyze}>{busy?'กำลังวิเคราะห์...':'วิเคราะห์ทุกแท็บ'}</button></div></div>}
    {preview&&<><div className="stats-grid">{[['ทั้งหมด',preview.summary.total],['พร้อมนำเข้า',preview.summary.ready],['ต้องตรวจสอบ',preview.summary.review],['ข้อมูลเดิม',preview.summary.duplicate]].map(([label,value])=><div className="card" key={label}><span className="muted">{label}</span><strong className="stat-number">{formatNumber(value,0)}</strong></div>)}</div><div className="card"><div className="section-title-row"><div><h3>Preview ก่อนลงฐานข้อมูล</h3><span className="muted">พบแท็บ {preview.found_sheets.join(' · ')} · เลือกแล้ว {selected.size}</span></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">ทุกแท็บ</option>{preview.found_sheets.map(s=><option key={s}>{s}</option>)}</select></div><div className="table-wrap" style={{maxHeight:560}}><table><thead><tr><th></th><th>แท็บ/แถว</th><th>วันที่/เดือน</th><th>โมดูล</th><th>ประเภท</th><th>ค่า</th><th>สถานะ</th></tr></thead><tbody>{visible.map(r=><tr key={r.row_id}><td><input type="checkbox" disabled={r.status!=='ready'} checked={selected.has(r.row_id)} onChange={e=>setSelected(current=>{const next=new Set(current);e.target.checked?next.add(r.row_id):next.delete(r.row_id);return next})}/></td><td>{r.sheet}<small className="muted"> แถว {r.row_number}</small></td><td>{r.entry.entry_date}</td><td>{MODULE_LABELS[r.entry.module]||r.entry.module}</td><td>{r.entry.material_name}</td><td>{formatNumber(r.entry.weight_kg??r.entry.quantity)} {r.entry.unit}</td><td><span className={`import-status ${r.status}`}>{STATUS[r.status]}</span>{r.issues.length>0&&<small> {r.issues.join(' · ')}</small>}</td></tr>)}</tbody></table></div><div className="form-actions bottom-actions"><button className="ghost" onClick={()=>setPreview(null)}>ยกเลิก</button><button className="primary" disabled={!selected.size||busy} onClick={commit}>{busy?'กำลังนำเข้า...':`นำเข้าครั้งเดียว ${selected.size} รายการ`}</button></div></div></>}
    <div className="card" style={{marginTop:18}}><div className="section-title-row"><h3><History size={18}/> ประวัติชุดนำเข้า</h3><button className="ghost" onClick={loadHistory}>รีเฟรช</button></div>{!history.length?<p className="muted">ยังไม่มีประวัติ</p>:<div className="table-wrap"><table><thead><tr><th>เวลา</th><th>ไฟล์</th><th>สถานะ</th><th>นำเข้า</th><th>ข้าม</th><th></th></tr></thead><tbody>{history.map(b=><tr key={b.id}><td>{new Date(b.created_at).toLocaleString('th-TH')}</td><td>{b.file_name}</td><td>{b.status}</td><td>{b.imported_rows}</td><td>{b.skipped_rows}</td><td>{canRollback&&b.status==='committed'&&<button className="ghost" disabled={busy} onClick={()=>rollback(b)}><RotateCcw size={15}/> ย้อนกลับ</button>}</td></tr>)}</tbody></table></div>}</div>
  </section>
}
